pipeline {
    agent none 
        stages {
            stage('Build') {
                agent { 
                    docker{
                    image 'node:16' 
                } 
                steps {
                    sh 'npm install'
                    // stash 'snake'
                }
            }
        }
    }
}
