pipeline {
    agent none 
    stages {
        stage('Build') {
            agent { 
                docker{
                   image 'node:16' 
            } 
            steps {
                sh 'npm install'
              stash 'snake'
            }
        }
//         stage(' Test') {
//             agent { docker 'openjdk:8-jre' } 
//             steps {
//                 echo 'Hello, JDK'
//                 sh 'java -version'
//             }
//         }
    }
}
